sudo: false

cache:
  directories:
    - $HOME/.m2/repository # maven
    - $HOME/.ivy2/cache # sbt
    - $HOME/.sbt/launchers # sbt
    - $HOME/.coursier/cache # sbt + coursier

language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.8

script:
  - mvn ++$TRAVIS_SCALA_VERSION coverage test coverageReport

notifications:
  email:
    - dushyant.it2007@gmail.com